version: '3'
networks:
  eventfinder:

services:
  db:
    image: mongo:3.4-xenial
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGODB_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGODB_PASS}
    networks:
      - eventfinder
    ports:
      - "27017:27017"
  web:
    container_name: web
    depends_on:
      - db
    build:
      context: .
    networks:
      - eventfinder
    ports:
      - "80:8080"
